; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -mtriple=x86_64-unknown-unknown -mattr=+avx10.2 | FileCheck %s --check-prefixes=CHECK

; AVX10.2 has a scalar bf16 compare, VCOMISBF16. It always flushes denormal
; inputs to zero, while the f32 promotion it replaces (vpslld $16 + vucomiss)
; compares bf16 denormals exactly, so it is only used in functions whose
; denormal-fp environment already flushes denormal inputs.

;===----------------------------------------------------------------------===;
; Predicates, with denormal inputs flushed: all of these use VCOMISBF16.
;===----------------------------------------------------------------------===;

define i1 @cmp_oeq(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_oeq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setnp %cl
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    andb %cl, %al
; CHECK-NEXT:    retq
  %r = fcmp oeq bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_ogt(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ogt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp ogt bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_oge(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_oge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setae %al
; CHECK-NEXT:    retq
  %r = fcmp oge bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_olt(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_olt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_ole(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ole:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    setae %al
; CHECK-NEXT:    retq
  %r = fcmp ole bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_one(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    retq
  %r = fcmp one bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_ord(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ord:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setnp %al
; CHECK-NEXT:    retq
  %r = fcmp ord bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_ueq(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ueq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %r = fcmp ueq bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_ugt(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    setb %al
; CHECK-NEXT:    retq
  %r = fcmp ugt bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_uge(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_uge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    setbe %al
; CHECK-NEXT:    retq
  %r = fcmp uge bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_ult(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setb %al
; CHECK-NEXT:    retq
  %r = fcmp ult bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_ule(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ule:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setbe %al
; CHECK-NEXT:    retq
  %r = fcmp ule bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_uno(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_uno:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setp %al
; CHECK-NEXT:    retq
  %r = fcmp uno bfloat %a, %b
  ret i1 %r
}

; oeq and une are the two predicates that need both ZF and PF, so they take two
; SETcc off the one VCOMISBF16. There is no VCOMXBF16 to fold them back into
; a single flag test.
define i1 @cmp_une(bfloat %a, bfloat %b) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_une:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setp %cl
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    orb %cl, %al
; CHECK-NEXT:    retq
  %r = fcmp une bfloat %a, %b
  ret i1 %r
}

;===----------------------------------------------------------------------===;
; Other users of the compare.
;===----------------------------------------------------------------------===;

; A bf16 operand loaded from memory is moved into an xmm register first: the
; compare matches through the packed VR128X form, so the f16mem folding variant
; of VCOMISBF16 does not apply here.
define i1 @cmp_olt_load(bfloat %a, ptr %p) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_olt_load:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovsh {{.*#+}} xmm1 = mem[0],zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %b = load bfloat, ptr %p
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

define void @cmp_ogt_br(bfloat %a, bfloat %b, ptr %p) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_ogt_br:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    jbe .LBB15_2
; CHECK-NEXT:  # %bb.1: # %then
; CHECK-NEXT:    movb $1, (%rdi)
; CHECK-NEXT:  .LBB15_2: # %exit
; CHECK-NEXT:    retq
  %c = fcmp ogt bfloat %a, %b
  br i1 %c, label %then, label %exit

then:
  store i8 1, ptr %p
  br label %exit

exit:
  ret void
}

define bfloat @cmp_olt_select(bfloat %a, bfloat %b, bfloat %x, bfloat %y) denormal_fpenv(ieee|preservesign) {
; CHECK-LABEL: cmp_olt_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovw %xmm3, %eax
; CHECK-NEXT:    vmovw %xmm2, %ecx
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    cmoval %ecx, %eax
; CHECK-NEXT:    vmovw %eax, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp olt bfloat %a, %b
  %r = select i1 %c, bfloat %x, bfloat %y
  ret bfloat %r
}

;===----------------------------------------------------------------------===;
; Denormal-fp environments that keep the f32 promotion.
;===----------------------------------------------------------------------===;

; Default is IEEE, so denormal inputs must compare exactly.
define i1 @cmp_olt_default(bfloat %a, bfloat %b) {
; CHECK-LABEL: cmp_olt_default:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpslld $16, %xmm0, %xmm0
; CHECK-NEXT:    vpslld $16, %xmm1, %xmm1
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

; Only denormal *outputs* are flushed here; inputs are still IEEE.
define i1 @cmp_olt_flush_output_only(bfloat %a, bfloat %b) denormal_fpenv(preservesign|ieee) {
; CHECK-LABEL: cmp_olt_flush_output_only:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpslld $16, %xmm0, %xmm0
; CHECK-NEXT:    vpslld $16, %xmm1, %xmm1
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

; A dynamic input mode is not known to flush.
define i1 @cmp_olt_dynamic(bfloat %a, bfloat %b) denormal_fpenv(ieee|dynamic) {
; CHECK-LABEL: cmp_olt_dynamic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpslld $16, %xmm0, %xmm0
; CHECK-NEXT:    vpslld $16, %xmm1, %xmm1
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

; The float: section only covers f32, so bf16 falls back on the default mode.
define i1 @cmp_olt_f32_only(bfloat %a, bfloat %b) denormal_fpenv(ieee, float: preservesign) {
; CHECK-LABEL: cmp_olt_f32_only:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpslld $16, %xmm0, %xmm0
; CHECK-NEXT:    vpslld $16, %xmm1, %xmm1
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

;===----------------------------------------------------------------------===;
; Denormal-fp environments that also flush inputs.
;===----------------------------------------------------------------------===;

define i1 @cmp_olt_flush_both(bfloat %a, bfloat %b) denormal_fpenv(preservesign) {
; CHECK-LABEL: cmp_olt_flush_both:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

define i1 @cmp_olt_positivezero(bfloat %a, bfloat %b) denormal_fpenv(positivezero) {
; CHECK-LABEL: cmp_olt_positivezero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

;===----------------------------------------------------------------------===;
; The AVX10.2 intrinsics keep selecting VCOMISBF16 regardless of the denormal
; mode: they name the instruction, so its flushing is what the caller asked for.
;===----------------------------------------------------------------------===;

define i32 @intrinsic_comi_eq(<8 x bfloat> %a, <8 x bfloat> %b) {
; CHECK-LABEL: intrinsic_comi_eq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vcomisbf16 %xmm1, %xmm0
; CHECK-NEXT:    setnp %al
; CHECK-NEXT:    sete %cl
; CHECK-NEXT:    andb %al, %cl
; CHECK-NEXT:    movzbl %cl, %eax
; CHECK-NEXT:    retq
  %r = call i32 @llvm.x86.avx10.vcomisbf16eq(<8 x bfloat> %a, <8 x bfloat> %b)
  ret i32 %r
}

define i32 @intrinsic_comi_lt(<8 x bfloat> %a, <8 x bfloat> %b) {
; CHECK-LABEL: intrinsic_comi_lt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    vcomisbf16 %xmm0, %xmm1
; CHECK-NEXT:    seta %al
; CHECK-NEXT:    retq
  %r = call i32 @llvm.x86.avx10.vcomisbf16lt(<8 x bfloat> %a, <8 x bfloat> %b)
  ret i32 %r
}

declare i32 @llvm.x86.avx10.vcomisbf16eq(<8 x bfloat>, <8 x bfloat>)
declare i32 @llvm.x86.avx10.vcomisbf16lt(<8 x bfloat>, <8 x bfloat>)
